### ISSUE TITLE
Consider `wordWrap: "on"` setting `configurationDefaults`

### ISSUE THREAD

**Issue by mrazauskas** [mdx-js/mdx-analyzer#342]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Currently VS Code sets the `editor.wordWrap` option to `"on"` for `.md` files through `configurationDefaults` contribution point:

https://github.com/microsoft/vscode/blob/35425d369ada2ba625304f9adb626332f13d1753/extensions/markdown-language-features/package.json#L682-L690

If the `.md` extension is changed to `.mdx` the word wrap is turn off.

### Solution

Consider adding `configurationDefaults` for `mdx` to VS Code extension:

```json
"configurationDefaults": {
  "[mdx]": {
    "editor.wordWrap": "on"
  }
}
```

Reference: https://code.visualstudio.com/updates/v1_10#_language-specific-editor-settings

### Alternatives

Using local VS Code settings for `mdx` language also works, but that could be useful improvement for the extension.

**Comment by remcohaszing** [comment]
TIL it’s possible to specify configuration defaults for languages.

I have mixed feelings about adding this. For markup languages such as markdown or reStructuredText, I see why word wrapping is useful for long lines. However, IMO it’s not as great when the lines are wrapped manually or by a formatter.

MDX isn’t just a markup language though. It mixes markdown and JavaScript. For the JavaScript parts I think word wrapping is a bad idea.

So while this is an interesting idea, I’m leaning towards no.

**Comment by wooorm** [comment]
Yeah I‘d wonder how it behaves for the embedded ESM/JSX/expressions.
Also, whitespace is significant in MDX. This shouldn’t break that.

**Comment by remcohaszing** [comment]
From what I can tell it’s an all-or-nothing approach. If word wrapping is on for paragraphs etc, it’s also on for ESM etc.

**Comment by mrazauskas** [comment]
To clarify, this is just a display setting. Having it does not alter files anyhow.

Also note that it wraps lines at the length of screen. That is right, the setting would also apply for JavaScript. Might be I am old-school or my VS Code skills are limited, but it is rare to have JavaScript which are longer than screen. Possible, of course! No doubt.

I understand that MDX formatting is relatively new thing. Prettier does not support it yet. I also don’t know how to setup formatting for MDX properly. `remark-lint` does the linting part, but for my understand that is not the same as formatting.

**Comment by wooorm** [comment]
I personally don‘t see very strong reasons to do this.
Or very strong against.
But I feel a bit more for against, as in, to not perform wrapping.
Also for markdown, I’d feel more for not doing wrapping, personally.

> but it is rare to have JavaScript which are longer than screen. Possible, of course! No doubt.

I’d say the same for markdown/MDX, because it’s often “hard” wrapped (manually)?

> I also don’t know how to setup formatting for MDX properly. remark-lint does the linting part, but for my understand that is not the same as formatting.

remark already does some formatting, if you add `remark-mdx`.
It doesn’t do the “wrapping” for prose though, but it does for JSX. It doesn’t format ESM/expressions either.
The work is tough, but if you’re interested in improving the formatting with wrapping, see https://github.com/syntax-tree/mdast-util-mdx-jsx/blob/15da3704395cd3c541dfcfe9fb28029674331f1c/lib/index.js and apply similar things to `mdast-util-to-markdown`, and do let me know if you need help, I can advise.

**Comment by remcohaszing** [comment]
> but it is rare to have JavaScript which are longer than screen. Possible, of course! No doubt.

I usually have a file explorer and 2 editors open next to each other. This fits most of the time, but not always. I think more people do this.

> I’d say the same for markdown/MDX, because it’s often “hard” wrapped (manually)?

I’ve seen both. This is why I think it’s desirable sometimes, and sometimes explicitly not.

I think it’s good to not explicitly override the editor defaults for a language unless there’s a clear benefit. Since this is a preference, I think we should close this issue.
