### ISSUE TITLE
[typescript-plugin] Doesn't understand component map

### ISSUE THREAD

**Issue by aaronadamsCA** [mdx-js/mdx-analyzer#467]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

MDX extension v1.8.9

### Link to runnable example

https://codesandbox.io/p/github/aaronadamsCA/mdx-issues/main?file=/src/mdx.mdx

### Steps to reproduce

You'll have to run the reproduction in an environment that supports Visual Studio Code extensions.

The TypeScript plugin doesn't seem to understand a component map in a `.mdx` file:

![image](https://github.com/user-attachments/assets/8246ea6c-66cd-4d43-a6e9-e62cb9cd6125)

### Expected behavior

No errors or warnings.

### Actual behavior

The plugin isn't recognizing the destructured `Component` and the JSX `<Component />` as the same object, whereas the actual MDX parser has no problem with this syntax.

**Comment by remcohaszing** [comment]
I see why this happens and have a tough idea how to fix it. It has to do with the scope analysis of virtual files in https://github.com/mdx-js/mdx-analyzer/blob/main/packages/language-service/lib/virtual-code.js. We will probably need to utilize the more detailed scopes returned by periscopic instead of only relying on the global scope. I will get to it when I get to it, but someone else can give it a try if they want.

The related tests are in https://github.com/mdx-js/mdx-analyzer/blob/vscode-mdx%401.8.9/packages/language-service/test/language-plugin.js.
