### ISSUE TITLE
Indentation in code blocks breaks syntax highlighting

### ISSUE THREAD

**Issue by alexisintech** [mdx-js/mdx-analyzer#472]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

unifiedjs.vscode-mdx v1.8.10

### Steps to reproduce

1. Create a new MDX file in VS Code
2. Copy the following code in to the document:
````
  ```js
  console.log('hi')
  ```

  ```js
  console.log('hi2')
  ```
````

### Expected behavior

Code blocks should have correct syntax highlighting, as shown in the following image

<img width="296" alt="Screenshot 2024-08-23 at 14 08 12" src="https://github.com/user-attachments/assets/3fd6f2b9-80ad-401b-9c4a-29256b30353b">

### Actual behavior

When indented, the syntax highlighting breaks after the end of the first code block (the last triple backtick ```)

<img width="296" alt="Screenshot 2024-08-23 at 14 08 04" src="https://github.com/user-attachments/assets/9ab8308a-6f99-4187-9d0b-02cd7c14a685">

### Runtime

Other (please specify in steps to reproduce)

### OS

macOS

**Comment by wooorm** [comment]
weird, cannot reproduce on https://wooorm.com/markdown-tm-language/, but can indeed reproduce in VS Code with this extension.

**Comment by remcohaszing** [comment]
The issue also appears on the `markdown-tm-language` playground. The version hosted on https://wooorm.com/markdown-tm-language/ is outdated.

![Screenshot of the `markdown-tm-language` playground with the issue reproduced](https://github.com/user-attachments/assets/d84581a5-0aeb-4e35-a8cc-b0db35adbba3)

The version on https://mdxjs.com/playground/ also uses an outdated grammar where the issue can’t be reproduced.

The issue is reproducible on https://shiki.style/.

**Comment by wooorm** [comment]
ok, think I have it
